// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "fbc1b044-034e-4c66-8e48-ac5a190f918e";

const char SSID[]               = "Tracker_25";    // Network SSID (name)
const char PASS[]               = "datakhatam";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "SVFfhQERJ9eaWVKCsYaFvCKqI";    // Secret device password


void onServoChange();
void onLightChange();
void onUltrasonicChange();
void onAcceXChange();
void onAcceYChange();

int servo;
int light;
float ultrasonic;
float acceX;
float acceY;


void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(servo, READWRITE, ON_CHANGE, onServoChange);
  ArduinoCloud.addProperty(light, READWRITE, ON_CHANGE, onLightChange);
  ArduinoCloud.addProperty(ultrasonic, READ, ON_CHANGE, onUltrasonicChange);
  ArduinoCloud.addProperty(acceX, READWRITE, ON_CHANGE, onAcceXChange);
  ArduinoCloud.addProperty(acceY, READWRITE, ON_CHANGE, onAcceYChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);







